### ISSUE TITLE
Crash with FacebookWrapper class

### ISSUE THREAD

**Issue by AbhijitKurane** [oneall/android-sdk#7]
Hi ,
When we call below method in onCreate method of Activity,
        `OAManager.getInstance().onCreate(this, savedInstanceState);`

We are getting crash as below,
```
java.lang.NoClassDefFoundError: com.oneall.oneallsdk.FacebookWrapper$SessionStatusCallback
               at com.oneall.oneallsdk.FacebookWrapper.<init>(FacebookWrapper.java:38)
               at com.oneall.oneallsdk.FacebookWrapper.getInstance(FacebookWrapper.java:57)
               at com.oneall.oneallsdk.OAManager.onCreate(OAManager.java:612)
```

Please let us know if we are missing something.

--
Thanks,
Abhijit

**Comment by SchlesserClaude** [comment]
Hello,

could you please try this:
https://github.com/oneall/ios-sdk/#build-settings

Regards,

**Comment by AbhijitKurane** [comment]
Hi,
Sorry, I don't have any iOS experience.
But let me check with my iOS colleagues.


--
Thanks,
Abhijit

**Comment by swapnalishinde** [comment]
Hey guys, 
This is iOS specific issue and its corresponding solution.

**Comment by AbhijitKurane** [comment]
Hello @SchlesserClaude ,
Did you observed this issue at your end?

--
Thanks,
Abhijit
